### PR TITLE
Fixed: tried to delete snapshots in current directory instead of backuploc + snapshotprefix wasn't added

### PR DESCRIPTION
**Pull request by efficiosoft**
Old backups couldn't be deleted because only their timestamp was passed to btrfs sub del. That only worked in case you ran btrfs-backup from the snapshot directory and didn't use a snapshot prefix.

I didn't inspect the code much further, but deleting old snapshots now works flawlessly.

Please review and merge if you appreciate it.

Thanks alot for this tool!

Regards
Robert

### CODE REVIEW

**Comment by cyberhuman** [comment]
I'm not really sure the snapshot prefix should be applied to the backup location, since once specified for the source snapshot it will be added to the destination as well, and this will for sure break many setups (mine for example :-) ). And one can add any prefix by editing the last argument anyway.

**Comment by cyberhuman** [comment]
OMG, I think I'm wrong. The prefix should be added indeed. Let me check my config.

**Comment by efficiosoft** [comment]
Hm, I'm going to look over it again later today. Thanks for the hint. But seems there is much more wrong with the way backups are deleted... I'll check that and come back later.

**Comment by cyberhuman** [comment]
I checked my config and it turns out I don't use `--snapshot-prefix`. I have mistaken it with `--snapshot-folder`, so no issue here. Sorry for the hassle.

**Comment by efficiosoft** [comment]
Ok, I only found btrfs-backup yesterday and thus any view on my changes from people that have been using it for a longer period of time than I did are heavily welcome :)

I also made some changes in the algorithm that chooses backups for deletion. It can now deal with directories at the backup location that don't belong to the current backup chain. For instance if one stores differently prefixed backups at the same location it won't delete the wrong subvolumes any longer.

Hope it gets merged.

**Comment by efficiosoft** [comment]
Hm, looking at the older pull requests it seems there is no reaction from @lordsutch.

Hence I'll keep my fork as an enhancement of btrfs-backup and am going to continue working on it.

Thanks to @lordsutch  for the original code!

**Comment by efficiosoft** [comment]
Closing this now because it grew far beyond its original scope and I don't want to mess up the original ``btrfs-backup`` repo. My future enhancements will go to https://github.com/efficiosoft/btrfs-backup, issues and PRs are always welcome.

Regards
Robert

**Comment by lordsutch** [comment]
Sorry for any inconvenience - I broke my leg in January and haven't really had time to get back to btrfs-backup or much of anything else beyond the essentials (i.e. my day job) since then. I'm happy to pull the commits in.

**Comment by efficiosoft** [comment]
Hi,

sorry for that. I just thought the project is dead because there were some pull requests completely unanswered since a couple of months. I'm glad to see you back again.

As you might have noticed, I did a almost complete rewrite of btrfs-backup at my fork. Unfortunately I opened this PR against the master branch of my fork, hence the changes can't easily be kept apart after all.

So what do you suggest?

**Comment by lordsutch** [comment]
Hmm. It may be best if I add a note to the README here to direct people to your fork as the preferred branch to work from in the future, since the refactoring you did would make it hard to pull in anything from anyone who's forked in the past, even though I think it was a good decision to move away from a monolithic design in favor of something a bit more modular and with support for setuptools etc.

Alternatively I can sync this repository to your fork and we can go from there. To be honest I've largely scratched my particular itch with btrfs-backup anyway (I tend to just throw things over the wall once they're Good Enough for my purposes) so if you want to take over that's fine.

That said I would like to at least have a fix for the underlying issue. It looks like if I just pull https://github.com/lordsutch/btrfs-backup/pull/13/commits/b3a1af41a3d25aa512b61cacbcfcbb315257a48b that should fix the underlying issue.

**Comment by efficiosoft** [comment]
In any case, pulling in changes up to https://github.com/lordsutch/btrfs-backup/commit/b3a1af41a3d25aa512b61cacbcfcbb315257a48b seems reasonable to get the fix that this commit was originally intended for.

I do really like the idea of btrfs-backup and would like to maintain it further. I know how things tend to go if one needs a specific feature and just writes something that fulfills his particular needs. Thank you for sharing that piece of code with us. That way I had a good starting point for my refacturing. It's the way free software works and I love this community-driven approach.

To get back to topic, because I deemed the project dead, I uploaded it to my PyPi account what AFAIK can't be undone, at least not without loosing the reserved name of the project. Thus I'd offer to take over the project, if you appreciate.

If you like, you could transfer the repo to me and be added yourself as a collaborator. Of course, if you do so, please do a full merge (no merge squashing) before. If you like that approach, please let me no, I'll then delete my copy after you synced all changes to be able to receive the transfer.

This probably is the best way to prevent other users from forking an outdated copy. Existing links/references would also stay intact.

What do you think about it?

**Comment by lordsutch** [comment]
That sounds like a plan. So here's what I'll do:

1. Merge the changes up to  https://github.com/lordsutch/btrfs-backup/commit/b3a1af41a3d25aa512b61cacbcfcbb315257a48b
2. Tag that as "legacy" or something similar, in case there are people who have changes based on it and don't want to migrate to the refactored code base for whatever reason.
3. Do a full merge of the rest of the changes.
4. Xfer the repository to you.

**Comment by efficiosoft** [comment]
That sounds great. Please comment again after you did the full merge so I can delete my fork.

**Comment by efficiosoft** [comment]
Additionally, I'll mention the legacy tag in README afterwards.

**Comment by lordsutch** [comment]
Ok, the full merge is done. Please double-check that everything in your fork made it over OK.

**Comment by efficiosoft** [comment]
Commits seem to be synced ok. I deleted the fork.

**Comment by efficiosoft** [comment]
Have a local clone just in case something goes terribly wrong.

**Pull request merged**
